interface AiProvenance {
  provider: string
  model: string
  promptVersion: string
  generatedAt: string
}

export function ProvenanceBadge({ provenance }: { provenance: AiProvenance }) {
  const isO3 = provenance.model === 'o3'
  const isDeterministic = provenance.provider === 'deterministic-demo'

  return (
    <div className="inline-flex items-center gap-2 px-2.5 py-1 bg-[#F4F6F9] border border-[#D0D7E3] rounded-full text-xs">
      <span className="w-1.5 h-1.5 rounded-full bg-[#003781]" />
      <span className="text-[#4A5568]">Generated by</span>
      <span className={`font-medium ${isO3 ? 'text-[#0066B2]' : isDeterministic ? 'text-[#4A5568]' : 'text-[#0A7C59]'}`}>
        {isDeterministic ? 'Deterministic Template' : `${provenance.provider} / ${provenance.model}`}
      </span>
      {isO3 && <span className="text-[#0066B2] text-xs">(reasoning model)</span>}
    </div>
  )
}
