import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db/index'
import { iacChanges, deployments, cloudResources, approvals, auditEvents } from '@/lib/db/schema'
import { eq, desc } from 'drizzle-orm'
import { transition, getCurrentState } from '@/lib/state-machine'
import { randomUUID } from 'crypto'
import * as crypto from 'crypto'
import * as fs from 'fs'
import { Paths, appendTransformLog, hashString, writeTextFile } from '@/lib/fs-service'

const BACKUP_TF_CONTENT = `# IT App X — Backup Infrastructure
# Control: BR0039-GR (Backup Geographic Redundancy Verification)
# Generated by: aoc-control-line[bot]
# Source: DORA Article 12(4) — Geographic separation of backup systems

resource "azurerm_recovery_services_vault" "rsv_app_x" {
  name                = "rsv-app-x-001-prod"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "Standard"
  storage_mode_type   = "GeoRedundant"

  tags = merge(local.common_tags, {
    control_id = "BR0039-GR"
    dora_ref   = "Article 12(4)"
  })
}

resource "azurerm_backup_policy_vm" "bkp_policy_app_x" {
  name                = "bkp-policy-app-x-001-daily"
  resource_group_name = azurerm_resource_group.rg.name
  recovery_vault_name = azurerm_recovery_services_vault.rsv_app_x.name

  backup {
    frequency = "Daily"
    time      = "02:00"
  }

  retention_daily {
    count = 30
  }

  tags = local.common_tags
}

resource "azurerm_backup_protected_vm" "vm_backup_app_x" {
  resource_group_name = azurerm_resource_group.rg.name
  recovery_vault_name = azurerm_recovery_services_vault.rsv_app_x.name
  source_vm_id        = azurerm_virtual_machine.app_x_vm.id
  backup_policy_id    = azurerm_backup_policy_vm.bkp_policy_app_x.id

  tags = local.common_tags
}
`

export async function POST(req: NextRequest) {
  try {
    const body = await req.json() as { decision: 'approved' | 'rejected'; reviewerComment?: string; reviewerName?: string }
    const { decision, reviewerComment = '', reviewerName = 'Platform Engineering Lead' } = body

    const { state, correlationId } = await getCurrentState()
    if (state !== 'IAC_PR_CREATED') {
      return NextResponse.json({ error: `Cannot approve IaC in state ${state}` }, { status: 400 })
    }

    const latestIac = db.select().from(iacChanges).orderBy(desc(iacChanges.createdAt)).limit(1).get()
    if (!latestIac) return NextResponse.json({ error: 'No IaC change found' }, { status: 404 })

    const approvalId = randomUUID()
    db.insert(approvals).values({
      id: approvalId,
      objectType: 'IacChange',
      objectId: latestIac.id,
      decision,
      reviewerComment,
      reviewerName,
      correlationId,
    }).run()

    if (decision === 'approved') {
      // ── File-system work: write backup.tf ──────────────────────────────────

      // Write actual backup.tf to disk
      writeTextFile(Paths.infra.backupTf, BACKUP_TF_CONTENT)

      // Compute a simulated commit SHA: SHA256 of the file content, first 8 chars
      const commitSha = crypto.createHash('sha256')
        .update(BACKUP_TF_CONTENT)
        .digest('hex')
        .slice(0, 8)

      // Compute a git-style diff (new file)
      const diffLines = BACKUP_TF_CONTENT.split('\n').map(l => `+${l}`)
      const diffContent = [
        `diff --git a/infra/it-app-x/backup.tf b/infra/it-app-x/backup.tf`,
        `new file mode 100644`,
        `index 0000000..${commitSha}`,
        `--- /dev/null`,
        `+++ b/infra/it-app-x/backup.tf`,
        `@@ -0,0 +1,${diffLines.length} @@`,
        ...diffLines,
      ].join('\n')

      // Update IaC record with real commit SHA and diff
      db.update(iacChanges)
        .set({ status: 'merged', commitSha, diffContent })
        .where(eq(iacChanges.id, latestIac.id))
        .run()

      // Append transform log
      const timestamp = new Date().toISOString()
      appendTransformLog({
        timestamp,
        transformationId: randomUUID(),
        sourceSystem: 'IaC Repository',
        sourceFile: Paths.infra.mainTf,
        sourceVersion: 'HEAD',
        sourceHash: hashString('no-backup-tf'),
        targetFile: Paths.infra.backupTf,
        targetVersion: commitSha,
        targetHash: hashString(BACKUP_TF_CONTENT),
        operation: 'IAC_WRITE',
        actor: reviewerName,
        approvalId,
        correlationId,
      })

      // ── Simulated deployment ───────────────────────────────────────────────
      const deploymentId = randomUUID()
      const simulatedAt = new Date().toISOString()
      const cloudStateSnapshot = {
        simulatedAt,
        commitSha,
        backupTfFile: Paths.infra.backupTf,
        resources: [
          { type: 'RecoveryVault', name: 'rsv-app-x-001-prod', storageRedundancy: 'GeoRedundant' },
          { type: 'BackupPolicy', name: 'bkp-policy-app-x-001-daily', frequency: 'Daily', retentionDays: 30 },
          { type: 'BackupProtectedItem', name: 'vm-app-x-001-backup', vmName: 'vm-app-x-001' },
        ],
      }

      db.insert(deployments).values({
        id: deploymentId,
        iacChangeId: latestIac.id,
        applicationId: 'APP-X-001',
        status: 'succeeded',
        simulatedAt,
        cloudStateSnapshot: JSON.stringify(cloudStateSnapshot),
        correlationId,
      }).run()

      // Update cloud state — add new resources derived from backup.tf
      db.insert(cloudResources).values({
        id: randomUUID(),
        applicationId: 'APP-X-001',
        type: 'RecoveryVault',
        name: 'rsv-app-x-001-prod',
        resourceId: '/subscriptions/sub-simulated-001/resourceGroups/rg-app-x-prod/providers/Microsoft.RecoveryServices/vaults/rsv-app-x-001-prod',
        config: JSON.stringify({ storageRedundancy: 'GeoRedundant', sku: 'Standard' }),
        tags: JSON.stringify({ app_id: 'APP-X-001', control_id: 'BR0039-GR', env: 'production', managed_by: 'terraform' }),
      }).run()

      db.insert(cloudResources).values({
        id: randomUUID(),
        applicationId: 'APP-X-001',
        type: 'BackupProtectedItem',
        name: 'vm-app-x-001-backup',
        config: JSON.stringify({ vmName: 'vm-app-x-001', policyName: 'bkp-policy-app-x-001-daily', status: 'Protected' }),
        tags: JSON.stringify({ app_id: 'APP-X-001' }),
      }).run()

      db.insert(auditEvents).values({
        id: randomUUID(),
        actor: reviewerName,
        action: 'IAC_APPROVED_AND_DEPLOYED',
        objectType: 'Deployment',
        objectId: deploymentId,
        outcome: 'success',
        correlationId,
        metadata: JSON.stringify({
          approvalId,
          reviewerComment,
          deploymentId,
          simulatedAt,
          commitSha,
          backupTfFile: Paths.infra.backupTf,
          backupTfHash: hashString(BACKUP_TF_CONTENT),
        }),
      }).run()

      const tx1 = await transition('DEPLOYMENT_APPROVED', reviewerName)
      if (!tx1.ok) return NextResponse.json({ error: tx1.error }, { status: 400 })

      const tx2 = await transition('DEPLOYED', 'system:deployment-runner')
      if (!tx2.ok) return NextResponse.json({ error: tx2.error }, { status: 400 })

      return NextResponse.json({
        ok: true,
        newState: tx2.newState,
        deploymentId,
        simulatedAt,
        commitSha,
        backupTfFile: Paths.infra.backupTf,
        backupTfHash: hashString(BACKUP_TF_CONTENT),
        diff: diffContent,
      })
    } else {
      db.update(iacChanges).set({ status: 'rejected' }).where(eq(iacChanges.id, latestIac.id)).run()

      db.insert(auditEvents).values({
        id: randomUUID(),
        actor: reviewerName,
        action: 'IAC_REJECTED',
        objectType: 'IacChange',
        objectId: latestIac.id,
        outcome: 'success',
        correlationId,
        metadata: JSON.stringify({ approvalId, reviewerComment }),
      }).run()

      const txResult = await transition('STANDARD_APPROVED', reviewerName)
      return NextResponse.json({ ok: true, newState: txResult.ok ? txResult.newState : 'STANDARD_APPROVED', approvalId })
    }
  } catch (err) {
    console.error('[Stage 2 Approve]', err)
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
